---
kind: pipeline
type: kubernetes
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.5.0
  commands:
  - until docker info; do echo Waiting Docker to become healthy; sleep 2; done;
  - dapper ci
  volumes:
  - name: dockersock
    path: /var/run

- name: github_binary_release
  image: ibuildthecloud/github-release:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  environment:
    DRONE_REPO_OWNER: mazzy89
  when:
    instance:
    - drone.hzk8s.k3s.mazzarino.cz
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "mazzy/k3os"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone.hzk8s.k3s.mazzarino.cz
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: arm64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/arm64
    target: "mazzy/k3os:${DRONE_TAG}"
    template: "mazzy/k3os:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone.hzk8s.k3s.mazzarino.cz
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- arm64
